### ISSUE TITLE
Path to 1.0

### ISSUE THREAD

**Issue by bcardarella** [DockYard/json_api_assert#1]
- [ ] links
- [ ] meta
- [ ] errors
- [x] `Ecto.Date` serialization (#2)
- [x] `Ecto.Time` serialization (#2)
- [x] `Ecto.DateTime` serialization (#2)
